
server:
  port:8082
spring:
  application:
    name:ZuulProxy

eureka:
   client:
     serviceUrl:
        defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
     serviceId: Auction-Service

